name: easyclimate-examples
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - numpy >= 1.24.3
    - xarray >= 0.17.0
    - geocat.viz
    - cartopy >= 0.20
    - xeofs >= 2.2.2
    - matplotlib
    - pandas >= 2.2.0
    - fast-barnes-py
    - oceans
    - intel-fortran-rt
    - dpcpp-cpp-rt
    - scipy >=1.8.0
    - statsmodels
    - geocat-comp
    - pyspharm-syl
    - windspharm-syl
    - dask
    - pymannkendall
    - flox
    - xarray-datatree
    - xarray_regrid
    - gsw_xarray
    - pooch
    - tqdm
    - zarr
    - metpy
    - easyclimate
